create table if not exists public.order_process_allowed_heltes (
  id bigint generated by default as identity primary key,
  order_process_id bigint not null references public.order_processes(id) on delete cascade,
  heltes_bteg_id text not null references public.heltes(bteg_id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  unique (order_process_id, heltes_bteg_id)
);

create table if not exists public.order_process_purchase_roles (
  id bigint generated by default as identity primary key,
  order_process_id bigint not null references public.order_processes(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  unique (order_process_id, role_id)
);

create index if not exists idx_order_process_allowed_heltes_process
  on public.order_process_allowed_heltes(order_process_id);

create index if not exists idx_order_process_allowed_heltes_heltes
  on public.order_process_allowed_heltes(heltes_bteg_id);

create index if not exists idx_order_process_purchase_roles_process
  on public.order_process_purchase_roles(order_process_id);

create index if not exists idx_order_process_purchase_roles_role
  on public.order_process_purchase_roles(role_id);

grant all on table public.order_process_allowed_heltes to anon;
grant all on table public.order_process_allowed_heltes to authenticated;
grant all on table public.order_process_allowed_heltes to service_role;

grant all on sequence public.order_process_allowed_heltes_id_seq to anon;
grant all on sequence public.order_process_allowed_heltes_id_seq to authenticated;
grant all on sequence public.order_process_allowed_heltes_id_seq to service_role;

grant all on table public.order_process_purchase_roles to anon;
grant all on table public.order_process_purchase_roles to authenticated;
grant all on table public.order_process_purchase_roles to service_role;

grant all on sequence public.order_process_purchase_roles_id_seq to anon;
grant all on sequence public.order_process_purchase_roles_id_seq to authenticated;
grant all on sequence public.order_process_purchase_roles_id_seq to service_role;
