create table if not exists public.food_report_daily_snapshot (
  id bigint generated by default as identity primary key,
  report_date date not null,
  dining_hall_id bigint not null references public.dining_hall(id),
  meal_type text not null,
  org_name text not null,
  dep_name text not null,
  heltes_name text not null,
  expected_count bigint not null default 0,
  actual_count bigint not null default 0,
  manual_override_total bigint not null default 0,
  extra_serving_total bigint not null default 0,
  wrong_location_total bigint not null default 0,
  source_finalized_at timestamp with time zone not null,
  is_final boolean not null default true,
  refreshed_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  unique (report_date, dining_hall_id, meal_type, org_name, dep_name, heltes_name)
);

create index if not exists idx_food_report_daily_snapshot_date_hall
  on public.food_report_daily_snapshot (report_date, dining_hall_id);

create index if not exists idx_food_report_daily_snapshot_org
  on public.food_report_daily_snapshot (org_name, dep_name, heltes_name);

create or replace function public.snapshot_food_report_day(
  p_date date,
  p_force boolean default false
)
returns integer
language plpgsql
security definer
set search_path = public, target
as $$
declare
  v_hall_id bigint;
  v_rows integer := 0;
  v_inserted integer := 0;
  v_finalized_at timestamp with time zone := now();
begin
  if p_date is null then
    raise exception 'p_date is required';
  end if;

  for v_hall_id in
    select distinct hall_id
    from (
      select id::bigint as hall_id
      from public.dining_hall

      union

      select dining_hall_id::bigint as hall_id
      from public.meal_logs
      where date = p_date
        and dining_hall_id is not null

      union

      select dining_hall_id::bigint as hall_id
      from public.sub_employee_meal_plans
      where date = p_date
    ) halls
    where hall_id is not null
  loop
    with
    expected_actual as (
      select
        v_hall_id as dining_hall_id,
        coalesce(nullif(org_name, ''), 'Байгууллага тодорхойгүй')::text as org_name,
        coalesce(nullif(dep_name, ''), 'Алба тодорхойгүй')::text as dep_name,
        coalesce(nullif(heltes_name, ''), 'Хэлтэс тодорхойгүй')::text as heltes_name,
        coalesce(nullif(meal_type, ''), 'unknown')::text as meal_type,
        sum(expected_count)::bigint as expected_count,
        sum(actual_count)::bigint as actual_count
      from public.get_meal_expected_vs_actual(p_date, v_hall_id::integer)
      group by 1, 2, 3, 4, 5
    ),
    org_lookup as (
      select bteg_id, max(name)::text as name
      from public.organization
      group by bteg_id
    ),
    alba_lookup as (
      select bteg_id, max(name)::text as name
      from public.alba
      group by bteg_id
    ),
    heltes_lookup as (
      select bteg_id, max(name)::text as name
      from public.heltes
      group by bteg_id
    ),
    special_logs as (
      select
        case
          when ml.sub_employee_id is not null
            then coalesce(sub_org.name, 'Гэрээт байгууллага тодорхойгүй')
          else coalesce(o.name, u.organization_id, 'Байгууллага тодорхойгүй')
        end::text as org_name,
        case
          when ml.sub_employee_id is not null
            then 'Гэрээт'
          else coalesce(a.name, u.department_name, 'Алба тодорхойгүй')
        end::text as dep_name,
        case
          when ml.sub_employee_id is not null
            then 'Гэрээт'
          else coalesce(h.name, u.heltes_name, 'Хэлтэс тодорхойгүй')
        end::text as heltes_name,
        coalesce(nullif(ml.meal_type, ''), 'unknown')::text as meal_type,
        count(*) filter (where ml.is_manual_override = true)::bigint as manual_override_total,
        count(*) filter (where ml.is_extra_serving = true)::bigint as extra_serving_total,
        count(*) filter (where ml.is_wrong_location = true)::bigint as wrong_location_total
      from public.meal_logs ml
      left join lateral (
        select u1.*
        from public.users u1
        where u1.id = ml.user_id

        union all

        select u2.*
        from public.users u2
        where ml.user_id is null
          and ml.sub_employee_id is null
          and u2.bteg_id = ml.bteg_id

        limit 1
      ) u on true
      left join org_lookup o on o.bteg_id = u.organization_id
      left join alba_lookup a on a.bteg_id = u.department_id
      left join heltes_lookup h on h.bteg_id = u.heltes_id
      left join public.sub_employee_for_food sef on sef.id = ml.sub_employee_id
      left join public.organization sub_org on sub_org.id = sef.org_id
      where ml.date = p_date
        and ml.dining_hall_id = v_hall_id
        and (
          ml.is_manual_override = true
          or ml.is_extra_serving = true
          or ml.is_wrong_location = true
        )
      group by 1, 2, 3, 4
    ),
    snapshot_rows as (
      select
        p_date as report_date,
        v_hall_id as dining_hall_id,
        coalesce(ea.meal_type, sl.meal_type) as meal_type,
        coalesce(ea.org_name, sl.org_name) as org_name,
        coalesce(ea.dep_name, sl.dep_name) as dep_name,
        coalesce(ea.heltes_name, sl.heltes_name) as heltes_name,
        coalesce(ea.expected_count, 0)::bigint as expected_count,
        coalesce(ea.actual_count, 0)::bigint as actual_count,
        coalesce(sl.manual_override_total, 0)::bigint as manual_override_total,
        coalesce(sl.extra_serving_total, 0)::bigint as extra_serving_total,
        coalesce(sl.wrong_location_total, 0)::bigint as wrong_location_total
      from expected_actual ea
      full outer join special_logs sl
        on sl.org_name = ea.org_name
       and sl.dep_name = ea.dep_name
       and sl.heltes_name = ea.heltes_name
       and sl.meal_type = ea.meal_type
    ),
    upserted as (
      insert into public.food_report_daily_snapshot (
        report_date,
        dining_hall_id,
        meal_type,
        org_name,
        dep_name,
        heltes_name,
        expected_count,
        actual_count,
        manual_override_total,
        extra_serving_total,
        wrong_location_total,
        source_finalized_at,
        is_final,
        refreshed_at
      )
      select
        report_date,
        dining_hall_id,
        meal_type,
        org_name,
        dep_name,
        heltes_name,
        expected_count,
        actual_count,
        manual_override_total,
        extra_serving_total,
        wrong_location_total,
        v_finalized_at,
        true,
        now()
      from snapshot_rows
      where expected_count <> 0
         or actual_count <> 0
         or manual_override_total <> 0
         or extra_serving_total <> 0
         or wrong_location_total <> 0
      on conflict (report_date, dining_hall_id, meal_type, org_name, dep_name, heltes_name)
      do update set
        expected_count = excluded.expected_count,
        actual_count = excluded.actual_count,
        manual_override_total = excluded.manual_override_total,
        extra_serving_total = excluded.extra_serving_total,
        wrong_location_total = excluded.wrong_location_total,
        source_finalized_at = excluded.source_finalized_at,
        is_final = true,
        refreshed_at = now()
      where p_force = true
         or public.food_report_daily_snapshot.is_final = false
      returning 1
    )
    select count(*) into v_inserted from upserted;

    v_rows := v_rows + v_inserted;
  end loop;

  return v_rows;
end;
$$;

create or replace function public.snapshot_due_food_reports()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report_date date := ((now() at time zone 'Asia/Ulaanbaatar')::date - 7);
begin
  return public.snapshot_food_report_day(v_report_date, false);
end;
$$;

create or replace function public.get_food_monthly_report(p_month date)
returns table (
  report_month date,
  dining_hall_id bigint,
  dining_hall_name text,
  org_name text,
  dep_name text,
  heltes_name text,
  meal_type text,
  expected_count bigint,
  actual_count bigint,
  manual_override_total bigint,
  extra_serving_total bigint,
  wrong_location_total bigint
)
language sql
stable
set search_path = public
as $$
  select
    date_trunc('month', fr.report_date)::date as report_month,
    fr.dining_hall_id,
    dh.name::text as dining_hall_name,
    fr.org_name,
    fr.dep_name,
    fr.heltes_name,
    fr.meal_type,
    sum(fr.expected_count)::bigint as expected_count,
    sum(fr.actual_count)::bigint as actual_count,
    sum(fr.manual_override_total)::bigint as manual_override_total,
    sum(fr.extra_serving_total)::bigint as extra_serving_total,
    sum(fr.wrong_location_total)::bigint as wrong_location_total
  from public.food_report_daily_snapshot fr
  left join public.dining_hall dh on dh.id = fr.dining_hall_id
  where fr.report_date >= date_trunc('month', p_month)::date
    and fr.report_date < (date_trunc('month', p_month)::date + interval '1 month')
  group by 1, 2, 3, 4, 5, 6, 7
  order by 3 nulls last, 4, 7;
$$;

revoke all on public.food_report_daily_snapshot from anon;
revoke all on public.food_report_daily_snapshot from authenticated;
grant select on public.food_report_daily_snapshot to authenticated;

revoke execute on function public.snapshot_food_report_day(date, boolean) from anon, authenticated;
revoke execute on function public.snapshot_due_food_reports() from anon, authenticated;
grant execute on function public.get_food_monthly_report(date) to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_extension
    where extname = 'pg_cron'
  ) then
    perform cron.unschedule(jobid)
    from cron.job
    where jobname = 'snapshot-food-report-daily';

    perform cron.schedule(
      'snapshot-food-report-daily',
      '30 0 * * *',
      'select public.snapshot_due_food_reports();'
    );
  end if;
end;
$$;
