create table if not exists public.order_suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  registration_number text,
  phone text,
  email text,
  address text,
  notes text,
  created_by bigint references public.profile(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  is_deleted boolean not null default false,
  constraint order_suppliers_name_not_blank check (length(btrim(name)) > 0)
);

create unique index if not exists idx_order_suppliers_registration_number
  on public.order_suppliers(registration_number)
  where registration_number is not null and is_deleted = false;

create index if not exists idx_order_suppliers_name
  on public.order_suppliers using gin (to_tsvector('simple', coalesce(name, '')));

create table if not exists public.order_purchase_batches (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  supplier_id bigint not null references public.order_suppliers(id),
  reference_number text,
  purchased_at date not null default current_date,
  paid_at date,
  notes text,
  created_by bigint references public.profile(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists idx_order_purchase_batches_order
  on public.order_purchase_batches(order_id);

create index if not exists idx_order_purchase_batches_supplier
  on public.order_purchase_batches(supplier_id);

create table if not exists public.order_purchase_documents (
  id uuid primary key default gen_random_uuid(),
  purchase_batch_id bigint not null references public.order_purchase_batches(id) on delete cascade,
  doc_type text not null check (doc_type in ('invoice', 'payment_receipt')),
  bucket text not null default 'order-purchase-documents',
  storage_path text not null,
  file_name text not null,
  mime_type text,
  file_size bigint,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_order_purchase_documents_batch
  on public.order_purchase_documents(purchase_batch_id);

create index if not exists idx_order_purchase_documents_type
  on public.order_purchase_documents(doc_type);

create table if not exists public.order_purchase_lines (
  id bigint generated by default as identity primary key,
  purchase_batch_id bigint not null references public.order_purchase_batches(id) on delete cascade,
  order_item_id bigint not null references public.order_items(id) on delete cascade,
  quantity real not null check (quantity > 0),
  unit_price numeric(14, 2) not null check (unit_price >= 0),
  currency text not null default 'MNT',
  vat_amount numeric(14, 2) not null default 0 check (vat_amount >= 0),
  discount_amount numeric(14, 2) not null default 0 check (discount_amount >= 0),
  notes text,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_order_purchase_lines_batch
  on public.order_purchase_lines(purchase_batch_id);

create index if not exists idx_order_purchase_lines_item
  on public.order_purchase_lines(order_item_id);

create or replace function public.set_order_purchase_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_order_suppliers_updated_at on public.order_suppliers;
create trigger set_order_suppliers_updated_at
  before update on public.order_suppliers
  for each row
  execute function public.set_order_purchase_updated_at();

drop trigger if exists set_order_purchase_batches_updated_at on public.order_purchase_batches;
create trigger set_order_purchase_batches_updated_at
  before update on public.order_purchase_batches
  for each row
  execute function public.set_order_purchase_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'order-purchase-documents',
  'order-purchase-documents',
  false,
  31457280,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.order_suppliers enable row level security;
alter table public.order_purchase_batches enable row level security;
alter table public.order_purchase_documents enable row level security;
alter table public.order_purchase_lines enable row level security;

drop policy if exists "Order purchase users can read suppliers" on public.order_suppliers;
create policy "Order purchase users can read suppliers"
  on public.order_suppliers
  for select
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can create suppliers" on public.order_suppliers;
create policy "Order purchase users can create suppliers"
  on public.order_suppliers
  for insert
  to authenticated
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can update suppliers" on public.order_suppliers;
create policy "Order purchase users can update suppliers"
  on public.order_suppliers
  for update
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'))
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can read batches" on public.order_purchase_batches;
create policy "Order purchase users can read batches"
  on public.order_purchase_batches
  for select
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can create batches" on public.order_purchase_batches;
create policy "Order purchase users can create batches"
  on public.order_purchase_batches
  for insert
  to authenticated
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can read documents" on public.order_purchase_documents;
create policy "Order purchase users can read documents"
  on public.order_purchase_documents
  for select
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can create documents" on public.order_purchase_documents;
create policy "Order purchase users can create documents"
  on public.order_purchase_documents
  for insert
  to authenticated
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can read lines" on public.order_purchase_lines;
create policy "Order purchase users can read lines"
  on public.order_purchase_lines
  for select
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can create lines" on public.order_purchase_lines;
create policy "Order purchase users can create lines"
  on public.order_purchase_lines
  for insert
  to authenticated
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can read purchase files" on storage.objects;
create policy "Order purchase users can read purchase files"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'order-purchase-documents'
    and public.has_permission(auth.uid(), 'order', 'purchase')
  );

drop policy if exists "Order purchase users can upload purchase files" on storage.objects;
create policy "Order purchase users can upload purchase files"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'order-purchase-documents'
    and public.has_permission(auth.uid(), 'order', 'purchase')
  );

grant select, insert, update on public.order_suppliers to authenticated;
grant select, insert on public.order_purchase_batches to authenticated;
grant select, insert on public.order_purchase_documents to authenticated;
grant select, insert on public.order_purchase_lines to authenticated;
grant all on public.order_suppliers to service_role;
grant all on public.order_purchase_batches to service_role;
grant all on public.order_purchase_documents to service_role;
grant all on public.order_purchase_lines to service_role;
grant usage, select on sequence public.order_suppliers_id_seq to authenticated;
grant usage, select on sequence public.order_purchase_batches_id_seq to authenticated;
grant usage, select on sequence public.order_purchase_lines_id_seq to authenticated;
