create table if not exists public.order_purchase_quotes (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  supplier_id bigint not null references public.order_suppliers(id),
  quote_number text,
  quote_date date not null default current_date,
  valid_until date,
  status text not null default 'draft' check (status in ('draft', 'selected', 'rejected')),
  notes text,
  created_by bigint references public.profile(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists idx_order_purchase_quotes_order
  on public.order_purchase_quotes(order_id);

create index if not exists idx_order_purchase_quotes_supplier
  on public.order_purchase_quotes(supplier_id);

create table if not exists public.order_purchase_quote_documents (
  id uuid primary key default gen_random_uuid(),
  quote_id bigint not null references public.order_purchase_quotes(id) on delete cascade,
  bucket text not null default 'order-purchase-quotes',
  storage_path text not null,
  file_name text not null,
  mime_type text,
  file_size bigint,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_order_purchase_quote_documents_quote
  on public.order_purchase_quote_documents(quote_id);

create table if not exists public.order_purchase_quote_lines (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.order_purchase_quotes(id) on delete cascade,
  order_item_id bigint not null references public.order_items(id) on delete cascade,
  quantity real not null check (quantity > 0),
  unit_price numeric(14, 2) not null check (unit_price >= 0),
  currency text not null default 'MNT',
  notes text,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_order_purchase_quote_lines_quote
  on public.order_purchase_quote_lines(quote_id);

create index if not exists idx_order_purchase_quote_lines_item
  on public.order_purchase_quote_lines(order_item_id);

drop trigger if exists set_order_purchase_quotes_updated_at on public.order_purchase_quotes;
create trigger set_order_purchase_quotes_updated_at
  before update on public.order_purchase_quotes
  for each row
  execute function public.set_order_purchase_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'order-purchase-quotes',
  'order-purchase-quotes',
  false,
  31457280,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.order_purchase_quotes enable row level security;
alter table public.order_purchase_quote_documents enable row level security;
alter table public.order_purchase_quote_lines enable row level security;

drop policy if exists "Order purchase users can read quotes" on public.order_purchase_quotes;
create policy "Order purchase users can read quotes"
  on public.order_purchase_quotes
  for select
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can create quotes" on public.order_purchase_quotes;
create policy "Order purchase users can create quotes"
  on public.order_purchase_quotes
  for insert
  to authenticated
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can update quotes" on public.order_purchase_quotes;
create policy "Order purchase users can update quotes"
  on public.order_purchase_quotes
  for update
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'))
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can read quote documents" on public.order_purchase_quote_documents;
create policy "Order purchase users can read quote documents"
  on public.order_purchase_quote_documents
  for select
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can create quote documents" on public.order_purchase_quote_documents;
create policy "Order purchase users can create quote documents"
  on public.order_purchase_quote_documents
  for insert
  to authenticated
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can read quote lines" on public.order_purchase_quote_lines;
create policy "Order purchase users can read quote lines"
  on public.order_purchase_quote_lines
  for select
  to authenticated
  using (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can create quote lines" on public.order_purchase_quote_lines;
create policy "Order purchase users can create quote lines"
  on public.order_purchase_quote_lines
  for insert
  to authenticated
  with check (public.has_permission(auth.uid(), 'order', 'purchase'));

drop policy if exists "Order purchase users can read quote files" on storage.objects;
create policy "Order purchase users can read quote files"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'order-purchase-quotes'
    and public.has_permission(auth.uid(), 'order', 'purchase')
  );

drop policy if exists "Order purchase users can upload quote files" on storage.objects;
create policy "Order purchase users can upload quote files"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'order-purchase-quotes'
    and public.has_permission(auth.uid(), 'order', 'purchase')
  );

grant select, insert, update on public.order_purchase_quotes to authenticated;
grant select, insert on public.order_purchase_quote_documents to authenticated;
grant select, insert on public.order_purchase_quote_lines to authenticated;
grant all on public.order_purchase_quotes to service_role;
grant all on public.order_purchase_quote_documents to service_role;
grant all on public.order_purchase_quote_lines to service_role;
grant usage, select on sequence public.order_purchase_quotes_id_seq to authenticated;
grant usage, select on sequence public.order_purchase_quote_lines_id_seq to authenticated;
